name: Android CI
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          distribution: "temurin"
          java-version: 11
      - name: Build with gradle
        run: ./gradlew build
